# Generated by Django 4.0.4 on 2022-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_adress_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='taskname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
