# Generated by Django 4.0.4 on 2022-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_taskname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(default='', max_length=200)),
                ('organization', models.CharField(default='', max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('required_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
