# Generated by Django 4.0.4 on 2022-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Volunteer',
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table='volunteer',
        ),
    ]
